version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
# Do not build on tags (GitHub only)
skip_tags: true
platform:
- x64
- Win32
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: premake5.exe vs2017
build:
  project: OpenParrot.sln
  verbosity: minimal
artifacts:
- path: build\bin\release\output\
  name: OpenParrot$(platform)
deploy:
- provider: GitHub
  release: OpenParrot$(platform)_$(APPVEYOR_BUILD_VERSION)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: a2B+6mDTHuBa0fw8nm739eGJIZBcZp0IenhKvvXvreLR6ZUoHg9pflMP8ahNUK6o
  repository: teknogods/OpenParrot
  artifact: build\bin\release\OpenParrot$(platform).zip